name: Go Checks

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  go-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'
      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          echo "${HOME}/bin" >> $GITHUB_PATH
      - name: Run golangci-lint
        run: task go/lint/run

  go-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'
      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          echo "${HOME}/bin" >> $GITHUB_PATH
      - name: Run tests
        run: task go/test/run
